-- V1: User accounts table.
-- UUID generated by application layer (UUID.randomUUID()).
-- password_hash stores BCrypt-encoded password (never plain text).
-- email is unique across the system (used as login identity).
CREATE TABLE users (
    id            VARCHAR(36)  NOT NULL PRIMARY KEY COMMENT '用户唯一标识，UUID格式 (User unique identifier, UUID format)',
    email         VARCHAR(255) NOT NULL COMMENT '用户邮箱，用于登录，全局唯一 (User email for login, globally unique)',
    username      VARCHAR(100) NOT NULL COMMENT '用户名 (Username)',
    password_hash VARCHAR(255) NOT NULL COMMENT 'BCrypt加密后的密码 (BCrypt hashed password, never plain text)',
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '账户创建时间 (Account creation timestamp)',
    updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间，自动更新 (Last update timestamp, auto-updated)',
    CONSTRAINT uq_users_email UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT '用户账户表，存储认证信息 (User accounts table storing authentication credentials)';
